name: Run React App with PM2

on:
  push:
    branches:
      - github-action

jobs:
  build:
    runs-on: self-hosted # Use the appropriate label for your self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Install PM2
        run: npm install pm2 -g

      - name: Delete Existing PM2 Process
        run: pm2 delete my-react-app || true

      - name: Start React App with PM2
        run: pm2 start "npm start" --name "my-react-app" --cwd "/home/icanio-10094/git/project/Linux"

      - name: List PM2 Processes After Start
        run: pm2 ps
