name: Run React App with PM2

on:
  push:
    branches:
      - github-action

jobs:
  build:
    runs-on: self-hosted # Use the appropriate label for your self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Change Directory to React App
        run: cd /home/icanio-10094/git/project/react-web
        
      - name: Pull Latest Changes
        run: git pull
        
      - name: Install Dependencies
        run: npm install

      - name: Delete Existing PM2 Process
        run: pm2 delete my-react-app

      - name: Start React App with PM2
        run: pm2 start "npm start" --name "my-react-app" 

      - name: List PM2 Processes After Start
        run: pm2 ps
